const Data =[
    {
        id:1,
        category:'Tourism',
        imgUrl:'https://www.planetware.com/photos-large/IND/india-top-attractions-taj-mahal.jpg',
        title:' The Taj Mahal, Agra',
        content: "Taj Mahal is also the world's most famous testimony to the power of love. Named after Mumtaz Mahal, the favorite wife of Emperor Shah Jahan, this most beautiful of mausoleums was begun upon her death in 286328 and took 20,000 workmen until 28648 to complete.The best time to visit is either at dawn or dusk when the atmosphere is brilliantly altered by the change in lighting. If possible, try to catch a view of the Taj Mahal's reflection from the far bank of the Yamuna River-it makes for a memorable (and safe) selfie.",
        fullcontent: "Taj Mahal is also the world's most famous testimony to the power of love. Named after Mumtaz Mahal, the favorite wife of Emperor Shah Jahan, this most beautiful of mausoleums was begun upon her death in 286328 and took 20,000 workmen until 28648 to complete.The best time to visit is either at dawn or dusk when the atmosphere is brilliantly altered by the change in lighting. If possible, try to catch a view of the Taj Mahal's reflection from the far bank of the Yamuna River-it makes for a memorable (and safe) selfie.        "
    },
    {
        id:2,
        category:'Tourism',
        imgUrl:'https://www.planetware.com/photos-large/IND/india-top-attractions-mecca-masjid.jpg',
        title:'Mecca Masjid, Hyderabad',
        content:"Construction of Hyderabad's Mecca Masjid, one of the world's largest mosques – and one of the oldest in India – began in 286284 during Mohammed Quli Qutub Shah's reign and took almost 80 years to complete.Other notable features include inscriptions from the Quran above many of the arches and doors, the exquisite roof of the main hall, and the cornices around the entire mosque structure. Look out for the exquisite floral motifs and friezes over the arches.",
        fullcontent:"Construction of Hyderabad's Mecca Masjid, one of the world's largest mosques – and one of the oldest in India – began in 286284 during Mohammed Quli Qutub Shah's reign and took almost 80 years to complete.Other notable features include inscriptions from the Quran above many of the arches and doors, the exquisite roof of the main hall, and the cornices around the entire mosque structure. Look out for the exquisite floral motifs and friezes over the arches."
    },
    {
        id:3,
        category:'LatestArticle',
        imgUrl:'https://images.unsplash.com/photo-1606203627178-c7bec545dff1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
        title:'The Beaches of Goa',
        content:"Long known within India as the go-to destination for those seeking a great beach holiday, Goa's beautiful western coastline, overlooking the Arabian Sea, has only recently been discovered by tourists from overseas. Goa's more than 60 miles of coastline is home to some of the world's loveliest beaches, each with their own particular appeal.While in Goa, be sure to visit the Bhagwan Mahavir Wildlife Sanctuary. This superb attraction is home to thick forests and plenty of fauna, including deer, monkeys, elephants, leopards, tigers, and black panthers, as well as India's famous king cobras, and some 200 species of birds.",
        fullcontent:"Long known within India as the go-to destination for those seeking a great beach holiday, Goa's beautiful western coastline, overlooking the Arabian Sea, has only recently been discovered by tourists from overseas. Goa's more than 60 miles of coastline is home to some of the world's loveliest beaches, each with their own particular appeal.While in Goa, be sure to visit the Bhagwan Mahavir Wildlife Sanctuary. This superb attraction is home to thick forests and plenty of fauna, including deer, monkeys, elephants, leopards, tigers, and black panthers, as well as India's famous king cobras, and some 200 species of birds."
    },
    {
        id:4,
        category:'Tourism',
        imgUrl:'https://www.planetware.com/photos-large/IND/india-top-attractions-ellora-caves.jpg',
        title:' The Ellora Caves, Aurangabad',
        content:"The famous monumental Ellora Caves were built between the 5th and 280th centuries by Buddhist, Jain, and Hindu monks, and make for an excellent excursion from Mumbai, some 300 kilometers to the west.The Hindu caves are much more complex and were carved from the top down, so scaffolding was not necessary. Of these, the best is the Kailasa Temple, an enormous rock-cut temple representing Mount Kailasa and requiring the removal of 200,000 tons of rock.",
        fullcontent:"The famous monumental Ellora Caves were built between the 5th and 280th centuries by Buddhist, Jain, and Hindu monks, and make for an excellent excursion from Mumbai, some 300 kilometers to the west.The Hindu caves are much more complex and were carved from the top down, so scaffolding was not necessary. Of these, the best is the Kailasa Temple, an enormous rock-cut temple representing Mount Kailasa and requiring the removal of 200,000 tons of rock."
    },
    {
        id:5,
        category:'Tourism',
        imgUrl:'https://wallpapercave.com/wp/wp6612913.jpg',
        title:' The Ganges River',
        content:"The Ganges River, or 'Ganga' after the Hindu goddess, has long been one of India's most revered natural wonders. It's also one of the country's leading attractions, drawing crowds of Indian nationals to partake in its religious ceremonies, as well as tourists to enjoy the splendor of this mighty river.",
        fullcontent:"The Ganges River, or 'Ganga' after the Hindu goddess, has long been one of India's most revered natural wonders. It's also one of the country's leading attractions, drawing crowds of Indian nationals to partake in its religious ceremonies, as well as tourists to enjoy the splendor of this mighty river."
    },
    {
        id:6,
        category:'Latest',
        imgUrl:'https://i.pinimg.com/564x/49/5d/ea/495dea22158ef71ac90c6490ed64c653.jpg',
        title:'Munnar, Kerala',
        content:"Described as God’s own country, Kerala is quite popular among travellers. It will render you speechless with its immersive cultural experience and the lush bounty of nature. If you are looking for a place to visit in india with family where you can kiss stress goodbye, here’s the place for you.",
        fullcontent:"Described as God’s own country, Kerala is quite popular among travellers. It will render you speechless with its immersive cultural experience and the lush bounty of nature. If you are looking for a place to visit in india with family where you can kiss stress goodbye, here’s the place for you."
    },
    {
        id:7,
        category:'Tourism',
        imgUrl:'https://www.holidify.com/images/bgImages/ARAKU-VALLEY.jpg',
        title:'Araku Valley,Andhra Pradesh',
        content:"Araku Valley is a comparatively unexplored hill station mostly visited by locals as a weekend getaway and is situated some 2820 kilometres away from Vishakhapatnam. If you're a tourist looking for exclusivity and tranquillity, Vistadome train leaves Vishakhapatnam at 6.50 AM, making way through 58 tunnels and passing over 84 bridges making way through the breathtaking landscape to reach Araku in approximately in 5 hours, go, catch that!",
        fullcontent:"Araku Valley is a comparatively unexplored hill station mostly visited by locals as a weekend getaway and is situated some 2820 kilometres away from Vishakhapatnam. If you're a tourist looking for exclusivity and tranquillity, Vistadome train leaves Vishakhapatnam at 6.50 AM, making way through 58 tunnels and passing over 84 bridges making way through the breathtaking landscape to reach Araku in approximately in 5 hours, go, catch that!"
    },
    {
        id:8,
        category:'Tourism',
        imgUrl:'https://www.holidify.com/images/compressed/3273.jpg?v=28.28',
        title:'Tirupati,Andhra Pradesh',
        content:"Situated in the Chittoor district of Andhra Pradesh, Tirupati is known for Lord Venkateshwara Temple, one of the most visited pilgrimage centres in the country. Tirumala is one of the seven hills in Tirupati, where the main temple is located. The temple is believed to be placed where Lord Venkateshwara took the form of an idol and is hence home to the diety Govinda. Tirupati is one of the oldest cities of India and finds mention in plenty of ancient Vedas and Puranas ",
        fullcontent:"Situated in the Chittoor district of Andhra Pradesh, Tirupati is known for Lord Venkateshwara Temple, one of the most visited pilgrimage centres in the country. Tirumala is one of the seven hills in Tirupati, where the main temple is located. The temple is believed to be placed where Lord Venkateshwara took the form of an idol and is hence home to the diety Govinda. Tirupati is one of the oldest cities of India and finds mention in plenty of ancient Vedas and Puranas "
    },
    {
        id:9,
        category:'Tourism',
        imgUrl:'https://www.trawell.in/admin/images/upload/025326672Lambasingi-viewpoint.jpg',
        title:'Lambasingi, Visakhapatnam ',
        content:"Fondly called the ‘Kashmir of Andhra Pradesh’, Lambasingi is a quaint hamlet nestled in Chintapalli Mandal in the richly forested Arakku Valley at an elevation of 28025 m above the sea level. On of the best kept secrets of Andhra Pradesh, the dainty village is known for its majestic hills, apple orchards and panoramic views of the adjoining valleys. Also known as Korra Bayalu, the village is the only place in all of South India that experiences snowfall as the temperatures drop significantly.",

        fullcontent:"Fondly called the ‘Kashmir of Andhra Pradesh’, Lambasingi is a quaint hamlet nestled in Chintapalli Mandal in the richly forested Arakku Valley at an elevation of 28025 m above the sea level. On of the best kept secrets of Andhra Pradesh, the dainty village is known for its majestic hills, apple orchards and panoramic views of the adjoining valleys. Also known as Korra Bayalu, the village is the only place in all of South India that experiences snowfall as the temperatures drop significantly."
    },
    {
        id:10,
        category:'Tourism',
        imgUrl:'https://live.staticflickr.com/744/32162136311_32941fb0a8_b.jpg',
        title:'Rk Beach,Vizag',
        content:"Visakhapatnam is known as the beach city of Andhra Pradesh with its alluring beaches attracting hordes of visitors every day. One of the most popular beaches of Vizag is Ramakrishna beach, more commonly known as RK beach bustling with young and old people alike.RK Beach gets its name from the Ramakrishna Mission ashram situated near the beach. With its serene waters and cool atmosphere, the beach offers a wonderful view of the countryside.",
        fullcontent:"Visakhapatnam is known as the beach city of Andhra Pradesh with its alluring beaches attracting hordes of visitors every day. One of the most popular beaches of Vizag is Ramakrishna beach, more commonly known as RK beach bustling with young and old people alike.RK Beach gets its name from the Ramakrishna Mission ashram situated near the beach. With its serene waters and cool atmosphere, the beach offers a wonderful view of the countryside."
    },
    {
        id:11,
        category:'Tollywood',
        imgUrl:'https://stat1.bollywoodhungama.in/wp-content/uploads/2019/03/RRR-2022.jpeg',
        title:'Tollywood-RRR',
        content:'RRR is a 2022 Indian Telugu-language epic action drama film directed by S. S. Rajamouli, The film stars N. T. Rama Rao Jr., Ram Charan, Ajay Devgn, Alia Bhatt,It centers on two real-life Indian revolutionaries, Alluri Sitarama Raju (Charan) and Komaram Bheem (Rama Rao), and their fight against the British Raj. The film grossed ₹28,2850–28,200 crore (US$2850–2860 million) worldwide, setting several box office records for an Indian film, including the third-highest-grossing Indian film. RRR is nominated in three categories at the 47th Saturn Awards including Best Action / Adventure Film, Best International Film, and Best Director.',
        fullcontent:'RRR is a 2022 Indian Telugu-language epic action drama film directed by S. S. Rajamouli, The film stars N. T. Rama Rao Jr., Ram Charan, Ajay Devgn, Alia Bhatt,It centers on two real-life Indian revolutionaries, Alluri Sitarama Raju (Charan) and Komaram Bheem (Rama Rao), and their fight against the British Raj. The film grossed ₹28,2850–28,200 crore (US$2850–2860 million) worldwide, setting several box office records for an Indian film, including the third-highest-grossing Indian film. RRR is nominated in three categories at the 47th Saturn Awards including Best Action / Adventure Film, Best International Film, and Best Director.'
    },
    {
        id:12,
        category:'Tollywood',
        imgUrl:'https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/pushpa--the-rise-et00129538-08-12-2021-01-21-46.jpg',
        title:'Pushpa: The Rise',
        content:'Pushpa: The Rise – Part 028 is a 20228 Indian Telugu-language action drama film[7] written and directed by Sukumar. It stars Allu Arjun as the titular character alongside Fahadh Faasil (his Telugu debut),The film is commercially successful, grossing ₹355–₹365 crore at the box office. The film emerged as the highest-grossing Indian film in 20228, and ranks among the highest-grossing Telugu films of all time.[28] It is also the 30th highest grossing Indian film of all time.',
        fullcontent:'Pushpa: The Rise – Part 028 is a 20228 Indian Telugu-language action drama film[7] written and directed by Sukumar. It stars Allu Arjun as the titular character alongside Fahadh Faasil (his Telugu debut),The film is commercially successful, grossing ₹355–₹365 crore at the box office. The film emerged as the highest-grossing Indian film in 20228, and ranks among the highest-grossing Telugu films of all time.[28] It is also the 30th highest grossing Indian film of all time.'
    },
    {
        id:54,
        category:'Tollywood',
        imgUrl:'https://pbs.twimg.com/media/FasCqTZUcAEndmp?format=jpg&name=large',
        title:'Godfather',
        content:"Godfather (stylized as GodFather) is an upcoming Indian Telugu-language political action-thriller film directed by Mohan Raja and produced by Ram Charan, R. B. Choudary and N. V. Prasad under Konidela Production Company and Super Good Films. A remake of the 2019 Malayalam film Lucifer, [2]the film stars Chiranjeevi in the title role alongside Salman Khan, Nayanthara, Puri Jagannadh, and Satyadev Kancharana.The film score and soundtrack album of the film is composed by Thaman S. The music rights were acquired by Saregama.",
        fullcontent:"Godfather (stylized as GodFather) is an upcoming Indian Telugu-language political action-thriller film directed by Mohan Raja and produced by Ram Charan, R. B. Choudary and N. V. Prasad under Konidela Production Company and Super Good Films. A remake of the 2019 Malayalam film Lucifer, [2]the film stars Chiranjeevi in the title role alongside Salman Khan, Nayanthara, Puri Jagannadh, and Satyadev Kancharana.The film score and soundtrack album of the film is composed by Thaman S. The music rights were acquired by Saregama.",
    },
    {
        id:13,
        category:'Tollywood',
        imgUrl:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTqUxfzVF-XFGltP_5vIp6K6dCJv3cPz5SJ7wK9vhtcpSKvmXCr',
        title:'Baahubali 2: The Conclusion',
        content:"Baahubali 2:Baahubali 2: The Conclusion is a 2017 Indian epic action film directed by S. S. Rajamouli, who co-wrote the film with V. Vijayendra Prasad. It was produced by Shobu Yarlagadda and Prasad Devineni under the banner Arka Media Works. The film was produced in Tollywood, the centre of Telugu language films in India and was filmed in both Telugu and Tamil languages simultaneously. The film features an ensemble cast including Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah, Ramya Krishna, Sathyaraj, Nassar, and Subbaraju. The second cinematic part in the Baahubali franchise, it is the follow-up to Baahubali: The Beginning, serving as both a sequel and a prequel.[7] The film is set in medieval India and follows the sibling rivalry between Amarendra Baahubali and Bhallaladeva; the latter conspires against the former and has him killed by Kattappa. Years later, Amarendra's son returns to avenge his death.Baahubali 2 was the first Telugu film to also release in 4K High Definition format.Grossing ₹28,8280 crore worldwide ($267 million)the film surpassed PK (20284) to briefly become the highest grossing Indian film of all time",
        fullcontent:"Baahubali 2:Baahubali 2: The Conclusion is a 2017 Indian epic action film directed by S. S. Rajamouli, who co-wrote the film with V. Vijayendra Prasad. It was produced by Shobu Yarlagadda and Prasad Devineni under the banner Arka Media Works. The film was produced in Tollywood, the centre of Telugu language films in India and was filmed in both Telugu and Tamil languages simultaneously. The film features an ensemble cast including Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah, Ramya Krishna, Sathyaraj, Nassar, and Subbaraju. The second cinematic part in the Baahubali franchise, it is the follow-up to Baahubali: The Beginning, serving as both a sequel and a prequel.[7] The film is set in medieval India and follows the sibling rivalry between Amarendra Baahubali and Bhallaladeva; the latter conspires against the former and has him killed by Kattappa. Years later, Amarendra's son returns to avenge his death.Baahubali 2 was the first Telugu film to also release in 4K High Definition format.Grossing ₹28,8280 crore worldwide ($267 million)the film surpassed PK (20284) to briefly become the highest grossing Indian film of all time",
    },
    {
        id:14,
        category:'Tollywood',
        imgUrl:'https://i2.cinestaan.com/image-bank/1500-1500/206001-207000/206467.jpg',
        title:'Karthikeya 2',
        content:'Karthikeya 2 is a 2022 Indian Telugu-language mystery action-adventure film[4][5] written and directed by Chandoo Mondeti.The plot follows Dr. Karthikeya who is on a quest to find the lost anklet of Lord Krishna.Box office	est. ₹286−2820 crore',
        fullcontent:'Karthikeya 2 is a 2022 Indian Telugu-language mystery action-adventure film[4][5] written and directed by Chandoo Mondeti.The plot follows Dr. Karthikeya who is on a quest to find the lost anklet of Lord Krishna.Box office	est. ₹286−2820 crore'
    },
    {
        id:15,
        category:'Latest',
        imgUrl:'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR-GJWOluiuP4BTtHHg6Kk68cuueul3mwQOMwueqol3kBMrT8c7',
        title:'KGF Chapter 2',
        content:'KGF Chapter 2 aka KGF 2 movie is a sequel to the blockbuster movie KGF and it is a period action film written and directed by Prashanth Neel.With earnings of ₹28,200–28,250 crore globally,[287] K.G.F: Chapter 2 is the third highest-grossing Indian film worldwide, and the second highest-grossing film in India. A sequel is in development.',
        fullcontent:'KGF Chapter 2 aka KGF 2 movie is a sequel to the blockbuster movie KGF and it is a period action film written and directed by Prashanth Neel.With earnings of ₹28,200–28,250 crore globally,[287] K.G.F: Chapter 2 is the third highest-grossing Indian film worldwide, and the second highest-grossing film in India. A sequel is in development.',
    },
    {
        id:16,
        category:'Hollywood',
        imgUrl:'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQA_-tL18_rj9zEcjN6n41NEaJm-kRNF9UeOtvksZ4z_OW6jRA9',
        title:'Avengers: Endgame (20289)',
        content:"Avengers: Endgame grossed $858.3 million in the United States and Canada, and $28.939 billion in other territories, for a worldwide total of $2.798 billion,[3] becoming the highest-grossing film of all time[2848] (until it was surpassed by Avatar (2009) due to the 20228 re-release in China[2849]), as well as the second-highest-grossing film of all time in the United States and Canada.[2850] Adjusted for inflation, Gone with the Wind (28939) remains the highest-grossing film, and Avengers: Endgame is the fifth-highest-grossing film of all time worldwide.[28528]",
        fullcontent:"Avengers: Endgame grossed $858.3 million in the United States and Canada, and $28.939 billion in other territories, for a worldwide total of $2.798 billion,[3] becoming the highest-grossing film of all time[2848] (until it was surpassed by Avatar (2009) due to the 20228 re-release in China[2849]), as well as the second-highest-grossing film of all time in the United States and Canada.[2850] Adjusted for inflation, Gone with the Wind (28939) remains the highest-grossing film, and Avengers: Endgame is the fifth-highest-grossing film of all time worldwide.[28528]",
    },
    {
        id:17,
        category:'Hollywood',
        imgUrl:'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',
        title:'Spider-Man: No Way Home (20228)',
        content:'Spider-Man: No Way Home is a 20228 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (20287) and Spider-Man: Far From Home (20289), and the 27th film in the Marvel Cinematic Universe (MCU). No Way Home has grossed over $28.9 billion worldwide, surpassing its predecessor as the highest-grossing film released by Sony Pictures. It became the highest-grossing film of 20228, the sixth-highest-grossing film of all time, the highest grossing Spider-Man film, and set several other box office records, including those for films released during the COVID-289 pandemic. ',
        fullcontent:'Spider-Man: No Way Home is a 20228 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (20287) and Spider-Man: Far From Home (20289), and the 27th film in the Marvel Cinematic Universe (MCU). No Way Home has grossed over $28.9 billion worldwide, surpassing its predecessor as the highest-grossing film released by Sony Pictures. It became the highest-grossing film of 20228, the sixth-highest-grossing film of all time, the highest grossing Spider-Man film, and set several other box office records, including those for films released during the COVID-289 pandemic. ',
    },
    {
        id:18,
        category:'Hollywood',
        imgUrl:'https://images.moviesanywhere.com/c07276e9473360730fdbc94baebc4236/4692c964-61ba-486d-9c77-939dbfba2f07.jpg',
        title:'The Lion King (20289)',
        content:'The Lion King is a 20289 American musical drama film directed and produced by Jon Favreau, written by Jeff Nathanson, United States on July 289, 20289, in the Dolby Cinema, RealD 3D and IMAX formats. It has grossed over $28.6 billion worldwide during its theatrical run, overtaking Frozen to become the highest-grossing animated film of all time. It also became the seventh-highest-grossing film of all time and the second-highest-grossing film of 20289. ',
        fullcontent:'The Lion King is a 20289 American musical drama film directed and produced by Jon Favreau, written by Jeff Nathanson, United States on July 289, 20289, in the Dolby Cinema, RealD 3D and IMAX formats. It has grossed over $28.6 billion worldwide during its theatrical run, overtaking Frozen to become the highest-grossing animated film of all time. It also became the seventh-highest-grossing film of all time and the second-highest-grossing film of 20289. ',
    },
    {
        id:19,
        category:'Hollywood',
        imgUrl:'https://www.the-numbers.com/images/movies/opusdata/Avengers-Infinity-War.jpg',
        title:'Avengers: Infinity War (20288)',
        content:'Avengers: Infinity War is a 20288 American superhero film based on the Marvel Comics superhero team the Avengers.The film was the fourth film and the first superhero film to gross over $2 billion worldwide, breaking numerous box office records, and becoming the highest-grossing film of 20288 and the fourth-highest-grossing film of all time both worldwide and in the United States and Canada. The film was nominated',
        fullcontent:'Avengers: Infinity War is a 20288 American superhero film based on the Marvel Comics superhero team the Avengers.The film was the fourth film and the first superhero film to gross over $2 billion worldwide, breaking numerous box office records, and becoming the highest-grossing film of 20288 and the fourth-highest-grossing film of all time both worldwide and in the United States and Canada. The film was nominated'
    },
    {
        id:20,
        category:'Hollywood',
        imgUrl:'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V28_.jpg',
        title:"The Dark Knight",
        content:"The Dark Knight is a 2008 superhero film directed by Christopher Nolan from a screenplay he co-wrote with his brother Jonathan.The Dark Knight broke several box office records and became the highest-grossing film of the year, fourth-highest-grossing film of its time, and the highest-grossing superhero film. It received critical acclaim for its mature tone and themes, visual style, and performances, particularly Ledger.He received several posthumous awards, including the Academy Award for Best Supporting Actor, making The Dark Knight the first comic book film to receive a major Academy Award.",
        fullcontent:"The Dark Knight is a 2008 superhero film directed by Christopher Nolan from a screenplay he co-wrote with his brother Jonathan.The Dark Knight broke several box office records and became the highest-grossing film of the year, fourth-highest-grossing film of its time, and the highest-grossing superhero film. It received critical acclaim for its mature tone and themes, visual style, and performances, particularly Ledger.He received several posthumous awards, including the Academy Award for Best Supporting Actor, making The Dark Knight the first comic book film to receive a major Academy Award.",
    },
    {
        id:21,
        category:'Hollywood',
        imgUrl:'https://upload.wikimedia.org/wikipedia/en/8/86/6_Underground_%28film%29.jpg',
        title:'6 Underground ',
        content:"6 Underground is a 20289 American vigilante action thriller film directed by Michael Bay,the film is one of the most expensive Netflix originals ever made.Netflix announced that the film had been viewed by over 83 million viewers on its service within its first month of release.",
        fullcontent:"6 Underground is a 20289 American vigilante action thriller film directed by Michael Bay,the film is one of the most expensive Netflix originals ever made.Netflix announced that the film had been viewed by over 83 million viewers on its service within its first month of release.",
    },
    {
        id:22,
        category:'LatestArticle',
        imgUrl:'https://upload.wikimedia.org/wikipedia/en/6/63/Godzilla_vs._Kong.png',
        title:'Godzilla vs. Kong',
        content:'Godzilla vs. Kong is a 20228 American monster film directed by Adam Wingard.It broke several pandemic box office records, and grossed over $470 million worldwide, against a production budget between $2855–200 million and a break-even point of $330 million, making it the eighth-highest-grossing film of 20228.',
        fullcontent:'Godzilla vs. Kong is a 20228 American monster film directed by Adam Wingard.It broke several pandemic box office records, and grossed over $470 million worldwide, against a production budget between $2855–200 million and a break-even point of $330 million, making it the eighth-highest-grossing film of 20228.',
    },
    {
        id:23,
        category:'Hollywood',
        imgUrl:'https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg',
        title:'Inception',
        content:'Inception is a 20280 science fiction action film[4][5][6] written and directed by Christopher Nolan.Inception grossed over $828 million worldwide, becoming the fourth-highest-grossing film of 20280. Considered one of the best films of the 20280s,[285] Inception won four Academy Awards (Best Cinematography, Best Sound Editing, Best Sound Mixing, and Best Visual Effects) and was nominated for four more: Best Picture, Best Original Screenplay, Best Art Direction, and Best Original Score.',
        fullcontent:'Inception is a 20280 science fiction action film[4][5][6] written and directed by Christopher Nolan.Inception grossed over $828 million worldwide, becoming the fourth-highest-grossing film of 20280. Considered one of the best films of the 20280s,[285] Inception won four Academy Awards (Best Cinematography, Best Sound Editing, Best Sound Mixing, and Best Visual Effects) and was nominated for four more: Best Picture, Best Original Screenplay, Best Art Direction, and Best Original Score.',
    },
    {
        id:24,
        category:'Hollywood',
        imgUrl:'https://upload.wikimedia.org/wikipedia/en/8/8c/The_Social_Network_film_poster.png',
        title:'The Social Network',
        content:"The Social Network is a 20280 American biographical drama film directed by David Fincher and written by Aaron Sorkin. Adapted from Ben Mezrich's 2009 book The Accidental Billionaires, it portrays the founding of social networking website Facebook and the resulting lawsuits.the film grossed $224 million on a $40 million budget and was widely acclaimed by critics. It was named one of the best films of the year by 78 critics, and named the best by 22 critics, the most of any film that year",
        fullcontent:"The Social Network is a 20280 American biographical drama film directed by David Fincher and written by Aaron Sorkin. Adapted from Ben Mezrich's 2009 book The Accidental Billionaires, it portrays the founding of social networking website Facebook and the resulting lawsuits.the film grossed $224 million on a $40 million budget and was widely acclaimed by critics. It was named one of the best films of the year by 78 critics, and named the best by 22 critics, the most of any film that year",
    },
    {
        id:25,
        category:'Hollywood',
        imgUrl:'https://www.themoviedb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        title:'Breaking Bad',
        content:"Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and filmed in Albuquerque, New Mexico, the series follows Walter White (Bryan Cranston), an underpaid, overqualified, and dispirited high-school chemistry teacher who is struggling with a recent diagnosis of stage-three lung cancer. White turns to a life of crime and partners with a former student, Jesse Pinkman (Aaron Paul), to produce and distribute crystal meth to secure his family's financial future before he dies, while navigating the dangers of the criminal underworld. The show aired on AMC from January 20, 2008, to September 29, 2013, consisting of five seasons for a total of 62 episodes.",
        fullcontent:"Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and filmed in Albuquerque, New Mexico, the series follows Walter White (Bryan Cranston), an underpaid, overqualified, and dispirited high-school chemistry teacher who is struggling with a recent diagnosis of stage-three lung cancer. White turns to a life of crime and partners with a former student, Jesse Pinkman (Aaron Paul), to produce and distribute crystal meth to secure his family's financial future before he dies, while navigating the dangers of the criminal underworld. The show aired on AMC from January 20, 2008, to September 29, 2013, consisting of five seasons for a total of 62 episodes.",
    },
    {
        id:26,
        category:'LatestArticle',
        imgUrl:'https://images.unsplash.com/photo-1534723328310-e82dad3ee43f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80',
        title:'Technology',
        content:'Tesla Chief Elon Musk is all geared up to deploy several humanoid robots named Tesla Bots in the Tesla factory. Four years ago, this Billionaire had said that they over relied on the robots and that resulted in a “production hell”. He had said that at certain jobs, humans are better than these humanoids.',
        fullcontent:'Tesla Chief Elon Musk is all geared up to deploy several humanoid robots named Tesla Bots in the Tesla factory. Four years ago, this Billionaire had said that they over relied on the robots and that resulted in a “production hell”. He had said that at certain jobs, humans are better than these humanoids.',
    },
    {
        id:27,
        category:'Technology',
        imgUrl:'https://www.port.ac.uk/-/media/images/news-events-and-blogs/blogs/2021/01-january/800-x-400-copy-of-copy-of-portsmouth-uni-team---ss-demo2.jpg',
        title:"Technology-1",
        content:"Soluta iure molestias totam, dolore nihil saepe tenetur vitae voluptas expedita numquam! Non rerum doloremque modi repellendus suscipit nostrum vel maiores nam? Pariatur similique optio beatae iure animi voluptatibus iste voluptas sunt quaerat odit dolore accusantium, itaque vel quod repellendus, architecto porro.",
        fullcontent:"Soluta iure molestias totam, dolore nihil saepe tenetur vitae voluptas expedita numquam! Non rerum doloremque modi repellendus suscipit nostrum vel maiores nam? Pariatur similique optio beatae iure animi voluptatibus iste voluptas sunt quaerat odit dolore accusantium, itaque vel quod repellendus, architecto porro.",
    },
    {
        id:28,
        category:'Latest',
        imgUrl:'https://cdn.pixabay.com/photo/2018/01/02/08/11/block-chain-3055701__340.jpg',
        title:'Technology',
        content:'artificial intelligence (AI) and blockchain concepts are spreading at a phenomenal rate. Both technologies have distinct degree of technological complexity and multi-dimensional business implications. However, a common misunderstanding about blockchain concept, in particular, is that blockchain is decentralized and is not controlled by anyone. But the underlying development of a blockchain system is still attributed to a cluster of core developers. ',
        fullcontent:'artificial intelligence (AI) and blockchain concepts are spreading at a phenomenal rate. Both technologies have distinct degree of technological complexity and multi-dimensional business implications. However, a common misunderstanding about blockchain concept, in particular, is that blockchain is decentralized and is not controlled by anyone. But the underlying development of a blockchain system is still attributed to a cluster of core developers. ',
    },
    {
        id:29,
        category:'Technology',
        imgUrl:'https://cdn.pixabay.com/photo/2016/11/19/14/00/code-1839406_960_720.jpg',
        title:"Technology-2",
        content:"THIS YEAR MARKS the 30th anniversary of the World Wide Web, so there's been a lot of pixels spilled on the initial promises of the web—one of which was the idea that you could select view source on any page and easily teach yourself what went into making it display like that. Here's the very first webpage, reproduced by the tinker-friendly programming website ",
        fullcontent:"THIS YEAR MARKS the 30th anniversary of the World Wide Web, so there's been a lot of pixels spilled on the initial promises of the web—one of which was the idea that you could select view source on any page and easily teach yourself what went into making it display like that. Here's the very first webpage, reproduced by the tinker-friendly programming website ",
    },
    {
        id:30,
        category:'Technology',
        imgUrl:'https://techcrunch.com/wp-content/uploads/2019/10/Heaviside-starry-night.jpg?w=1390&crop=1',
        title:'Technology-3',
        content:"Kitty Hawk, the electric aviation startup founded and led by the ‘godfather of self-driving cars’ Sebastian Thrun and backed by Google co-founder Larry Page, is shutting down.The company said in a tweet and on a post in LinkedIn that it was winding down “We have made the decision to wind down Kittyhawk. We’re still working on the details of what’s next,” the posts on social media read.",
        fullcontent:"Kitty Hawk, the electric aviation startup founded and led by the ‘godfather of self-driving cars’ Sebastian Thrun and backed by Google co-founder Larry Page, is shutting down.The company said in a tweet and on a post in LinkedIn that it was winding down “We have made the decision to wind down Kittyhawk. We’re still working on the details of what’s next,” the posts on social media read.",
    },
    {
        id:31,
        category:'Fitness',
        imgUrl:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
        title:'Fitness-1',
        content:'Regular physical activity is one of the most important things you can do for your health. Being physically active can improve your brain health, help manage weight, reduce the risk of disease, strengthen bones and muscles, and improve your ability to do everyday activities.',
        fullcontent:'Regular physical activity is one of the most important things you can do for your health. Being physically active can improve your brain health, help manage weight, reduce the risk of disease, strengthen bones and muscles, and improve your ability to do everyday activities.',
    },
    {
        id:32,
        category:'LatestArticle',
        imgUrl:'https://lmimirror3pvr.azureedge.net/static/media/26490/3c31aefe-c655-438d-8cb1-02c9e1bcc764/pushups_960x540px.jpg',
        title:'PUSH-UPS',
        content:'Push-ups are one of the most popular measures of fitness, so it makes sense that this article was a popular read. Experts say whether you do them on your knees or toes, push-ups are one exercise worth mastering – and here they provide some top tips, including the three common mistakes to avoid! Get the latest push-up insights.',
        fullcontent:'Push-ups are one of the most popular measures of fitness, so it makes sense that this article was a popular read. Experts say whether you do them on your knees or toes, push-ups are one exercise worth mastering – and here they provide some top tips, including the three common mistakes to avoid! Get the latest push-up insights.',
    },
    {
        id:33,
        category:'Fitness',
        imgUrl:'https://cdn.shopify.com/s/files/1/1876/4703/articles/shutterstock_1495111259_1000x.jpg?v=1636561230',
        title:'Lunges ',
        content:"Lunges increase muscle mass to build up strength and tone your body, especially your core, butt, and legs. Improving your appearance isn't the main benefit of shaping up your body, as you'll also improve your posture and range of motion.This resistance exercise is popular for its ability to strengthen your back, hips, and legs, while improving mobility and stability. Lunges are ideal for those wishing to get stronger and for current athletes, including runners and cyclists.",
        fullcontent:"Lunges increase muscle mass to build up strength and tone your body, especially your core, butt, and legs. Improving your appearance isn't the main benefit of shaping up your body, as you'll also improve your posture and range of motion.This resistance exercise is popular for its ability to strengthen your back, hips, and legs, while improving mobility and stability. Lunges are ideal for those wishing to get stronger and for current athletes, including runners and cyclists.",
    },
    {
        id:34,
        category:'Fitness',
        imgUrl:'https://thumbs.dreamstime.com/b/sport-man-doing-squat-posture-yoga-mat-fitness-gym-condominium-urban-people-lifestyles-workout-concept-149836387.jpg',
        title:'Squats',
        content:"The squat is a fundamental movement pattern that requires multiple joint and muscle integration. Babies squat perfectly. And then we unlearn this in favor of bending over.As a dynamic strength training exercise, squats require several muscles in your upper and lower body to work together simultaneously.Adding squats to your workouts can help boost your exercise performance, decrease your risk of injury, and keep you moving more easily throughout the day. But these are just a few of the benefits.",
        fullcontent:"The squat is a fundamental movement pattern that requires multiple joint and muscle integration. Babies squat perfectly. And then we unlearn this in favor of bending over.As a dynamic strength training exercise, squats require several muscles in your upper and lower body to work together simultaneously.Adding squats to your workouts can help boost your exercise performance, decrease your risk of injury, and keep you moving more easily throughout the day. But these are just a few of the benefits.",
    },
    {
        id:35,
        category:'Fitness',
        imgUrl:'https://cdn2.stylecraze.com/wp-content/uploads/2013/11/796_12-Effective-Baba-Ramdev-Yoga-Exercises-For-Eyes_236779663.jpg.webp',
        title:'Yoga',
        content:'The word “yoga” comes from the root word “yuj,” which means “to yoke” or “to bind.” The word itself has numerous meanings, from an astrological conjunction to matrimony, with the underlying theme being connection.',
        fullcontent:'The word “yoga” comes from the root word “yuj,” which means “to yoke” or “to bind.” The word itself has numerous meanings, from an astrological conjunction to matrimony, with the underlying theme being connection.',
    },
    {
        id:36,
        category:'Food',
        imgUrl:'https://www.jacadatravel.com/wp-content/uploads/fly-images/316518/iStock-502019013-552x310-cc.jpg',
        title:' Masala dosa',
        content:"Arguably South India’s most renowned culinary export, masala dosas are famous the world over. A sort of Indian pancake, dosas are made from a thin batter consisting of rice, flour and lentils. Making dosas is no easy task, with the batter mixture having to soak in water for at least 24 hours before it can be shaped. Once ready, the batter is ladled onto a hot tava (griddle pan) and shaped in a similar way to how the French would shape a crepe.Traditionally, dosas are served folded in half and stuffed with potatoes. Accompaniments like hot sambar give the dish a spicy edge, and whatever you stuff them with, dosas are sure to provide a tasty yet satisfying meal. ",
        fullcontent:"Arguably South India’s most renowned culinary export, masala dosas are famous the world over. A sort of Indian pancake, dosas are made from a thin batter consisting of rice, flour and lentils. Making dosas is no easy task, with the batter mixture having to soak in water for at least 24 hours before it can be shaped. Once ready, the batter is ladled onto a hot tava (griddle pan) and shaped in a similar way to how the French would shape a crepe.Traditionally, dosas are served folded in half and stuffed with potatoes. Accompaniments like hot sambar give the dish a spicy edge, and whatever you stuff them with, dosas are sure to provide a tasty yet satisfying meal. ",
    },
    {
        id:37,
        category:'Food',
        imgUrl:'https://static1.thetravelimages.com/wordpress/wp-content/uploads/2019/08/5-Tandoori-Chicken-1.jpg?q=50&fit=crop&w=1500&dpr=1.5',
        title:'Tandoori Chicken',
        content:"Tandoori chicken is another North Indian dish that may have been around in 3000 BC. Tandoori Chicken derives its name from the vessel it's cooked in, known as a Tandoor Oven. It is a cylindrical-shaped oven that is powered by burning wood or charcoal. The Tandoor Oven is made of either clay or metal and offers a distinct taste to meals cooked within it. Tandoori Chicken consists of chicken marinated for a few days in a mixture of yogurt and tandoori masala, a blend of traditional Indian spices. Following this, the chicken is then cooked.",
        fullcontent:"Tandoori chicken is another North Indian dish that may have been around in 3000 BC. Tandoori Chicken derives its name from the vessel it's cooked in, known as a Tandoor Oven. It is a cylindrical-shaped oven that is powered by burning wood or charcoal. The Tandoor Oven is made of either clay or metal and offers a distinct taste to meals cooked within it. Tandoori Chicken consists of chicken marinated for a few days in a mixture of yogurt and tandoori masala, a blend of traditional Indian spices. Following this, the chicken is then cooked.",
    },
    {
        id:38,
        category:'Food',
        imgUrl:'https://upload.wikimedia.org/wikipedia/commons/4/40/Pootharekulu_dry_fruits.jpg',
        title:'Andhra Pradesh: Pootharekulu',
        content:'Pootharekulu literally means coated sheets of sugar preparation. They are made by making thin wrappers prepared from rice flour, pure ghee and lots of powdered sugar.',
        fullcontent:'Pootharekulu literally means coated sheets of sugar preparation. They are made by making thin wrappers prepared from rice flour, pure ghee and lots of powdered sugar.',
    },
    {
        id:39,
        category:'Food',
        imgUrl:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aHlkZXJhYmFkJTIwYmlyeWFuaXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60,',
        title:'Hyderabadi: Biryani',
        content:"The authentic Hyderabadi biryani is meticulously prepared in the 'Kutchi' (raw) biryani style, in which raw rice and raw meat are cooked together in a 'handi' (earthen pot) with spices and a little bit of water. “It takes meticulous planning and a lot of time to prepare Hyderabadi biryani.",
        fullcontent:"The authentic Hyderabadi biryani is meticulously prepared in the 'Kutchi' (raw) biryani style, in which raw rice and raw meat are cooked together in a 'handi' (earthen pot) with spices and a little bit of water. “It takes meticulous planning and a lot of time to prepare Hyderabadi biryani.",
    },
    {
        id:40,
        category:'Food',
        imgUrl:'https://images.unsplash.com/photo-1615719413546-198b25453f85?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80',
        title:'Pizza',
        content:'pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot.',
        fullcontent:'pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot.',
    },
    {
    id: 41,
    title: "Fitness",
    imgUrl: "https://cdn.pixabay.com/photo/2016/03/27/23/00/weight-lifting-1284616_960_720.jpg",
    content:
      "Soluta iure molestias totam, dolore nihil saepe tenetur vitae voluptas expedita numquam! Non rerum doloremque modi repellendus suscipit nostrum vel maiores nam? Pariatur similique optio beatae iure animi voluptatibus iste voluptas sunt quaerat odit dolore accusantium, itaque vel quod repellendus, architecto porro.",
    category: "LatestStories",
  },
  {
    id: 42,
    title: "Hollywood",
    imgUrl: "https://1.bp.blogspot.com/-Gcf0tNXdbpc/XTgG9Vi1gGI/AAAAAAAAS3U/_gNEKdS_mrktYw_almNKBc8pOkRT4IejgCLcBGAs/s1600/alita.jpg",
    content:
      "Soluta iure molestias totam, dolore nihil saepe tenetur vitae voluptas expedita numquam! Non rerum doloremque modi repellendus suscipit nostrum vel maiores nam? Pariatur similique optio beatae iure animi voluptatibus iste voluptas sunt quaerat odit dolore accusantium, itaque vel quod repellendus, architecto porro.",
    Date: "Release:18th April,2014",
    category: "LatestStories",
  },
  {
    id: 42,
    title: "Foods",
    imgUrl: "https://images.unsplash.com/photo-1529973565457-a60a2ccf750d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    content:
      "Soluta iure molestias totam, dolore nihil saepe tenetur vitae voluptas expedita numquam! Non rerum doloremque modi repellendus suscipit nostrum vel maiores nam? Pariatur similique optio beatae iure animi voluptatibus iste voluptas sunt quaerat odit dolore accusantium, itaque vel quod repellendus, architecto porro.",
      category: "LatestStories",
  },
  {
    id: 43,
    title: "vada pav",
    imgUrl: "https://www.jacadatravel.com/wp-content/uploads/fly-images/316521/iStock-1157170530-552x310-cc.jpg",
    content:
      "Originating in the traditionally vegetarian state of Maharashtra, vada pav is as close as Indian cuisine gets to veggie burgers. One for carb lovers, vada pav consists of a deep fried potato dumpling placed neatly inside a small bun. The finger food delicacy is generally accompanied by a couple of chutneys and a green chilli, to appeal to the spice loving palettes of Indians up and down the country. Also called a Bombay burger, these mini potato buns can be found in street food stalls across the city of Mumbai.",
      fullcontent:
      "Originating in the traditionally vegetarian state of Maharashtra, vada pav is as close as Indian cuisine gets to veggie burgers. One for carb lovers, vada pav consists of a deep fried potato dumpling placed neatly inside a small bun. The finger food delicacy is generally accompanied by a couple of chutneys and a green chilli, to appeal to the spice loving palettes of Indians up and down the country. Also called a Bombay burger, these mini potato buns can be found in street food stalls across the city of Mumbai.",
    Date: "Release:18th April,2014",
    category: "Food",
  },
  {
    id:44,
    title:"Idli",
    imgUrl: "https://www.jacadatravel.com/wp-content/uploads/fly-images/316526/iStock-1024549286-552x310-cc.jpg",
    content: "Popular across South India, idli are often thought of as the breakfast versions of dosa. Eaten at the start of the day, idli are a type of light savoury rice cake. Made by steaming a batter consisting of fermented black lentils and rice, these rice cakes are dangerously easy to eat. Since idli are pretty bland on their own, these mini pancake-like breakfast staples are served alongside sambar, coconut based chutneys, or spicy fish curries. Over the years, idli has evolved into many different varieties, so you’re sure to find one that satisfies your taste buds.",
    fullcontent: "Popular across South India, idli are often thought of as the breakfast versions of dosa. Eaten at the start of the day, idli are a type of light savoury rice cake. Made by steaming a batter consisting of fermented black lentils and rice, these rice cakes are dangerously easy to eat. Since idli are pretty bland on their own, these mini pancake-like breakfast staples are served alongside sambar, coconut based chutneys, or spicy fish curries. Over the years, idli has evolved into many different varieties, so you’re sure to find one that satisfies your taste buds.",
    category:"Food"
  },
  {
    id:45,
    title:"Ras malai",
    imgUrl: "https://cdn.tasteatlas.com//Images/Dishes/b53ee1a62b704a36b63361822681ed47.jpg?w=905&h=510",
    content: "Ras malai is a popular Indian dessert consisting of white cream, sugar, milk, and cardamom-flavored paneer cheese known as chhana. Almonds, cashews, and saffron are often added to the dessert. Ras malai is of West Bengali origins, and is sometimes described as a rich cheesecake without a crust.",
    fullcontent: "Ras malai is a popular Indian dessert consisting of white cream, sugar, milk, and cardamom-flavored paneer cheese known as chhana. Almonds, cashews, and saffron are often added to the dessert. Ras malai is of West Bengali origins, and is sometimes described as a rich cheesecake without a crust.",
    category:"Food"
  },
  {
    id:46,
    title:"Gulab jamun",
    imgUrl: "https://cdn.tasteatlas.com//Images/Dishes/23fba80da08c46ceba5a99a5b1f1f200.jpg?w=905&h=510",
    content: "Gulab jamun is a dessert based on milk solids that are kneaded into a dough, shaped into balls, and deep-fried in ghee. The balls then get soaked in a sugary concoction flavored with saffron, green cardamom, and rose water. When served, gulab jamun is often garnished with dried nuts to further enhance its flavors.",
    fullcontent: "Gulab jamun is a dessert based on milk solids that are kneaded into a dough, shaped into balls, and deep-fried in ghee. The balls then get soaked in a sugary concoction flavored with saffron, green cardamom, and rose water. When served, gulab jamun is often garnished with dried nuts to further enhance its flavors.",
    category:"Food"
  },
  {
    id:47,
    title:"Panipuri",
    imgUrl: "https://cdn.tasteatlas.com//Images/Dishes/b01fa4c9920d42df9ef472fd4f8e6fda.jpg?w=905&h=510",
    content: "Panipuri is a street snack that is extremely popular in India, Bangladesh, Pakistan, and Nepal. Small in size, it consists of a hollow puri that is fried until crispy, then stuffed with a combination of flavored water called pani, tamarind chutney, chaat masala, potatoes, onions, hot chillis, and chickpeas.",
    fullcontent: "Panipuri is a street snack that is extremely popular in India, Bangladesh, Pakistan, and Nepal. Small in size, it consists of a hollow puri that is fried until crispy, then stuffed with a combination of flavored water called pani, tamarind chutney, chaat masala, potatoes, onions, hot chillis, and chickpeas.",
    category:"Food"
  },
  {
    id:48,
    title:"Samosa",
    imgUrl: "https://cdn.tasteatlas.com//Images/Dishes/e668e32ae1a3423c95fbd4d77f8c940c.jpg?w=905&h=510",
    content: "Due to their crunchy texture and a variety of different flavors, samosas provide a perfect introduction to the world of Indian cuisine for newcomers. These deep-fried, triangular pastries are filled with a variety of ingredients ranging from vegetables to meat, such as onions, lentils, spiced potatoes, peas, or ground meat.",
    fullcontent: "Due to their crunchy texture and a variety of different flavors, samosas provide a perfect introduction to the world of Indian cuisine for newcomers. These deep-fried, triangular pastries are filled with a variety of ingredients ranging from vegetables to meat, such as onions, lentils, spiced potatoes, peas, or ground meat.",
    category:"Food"
  },
  {
        id:49,
        category:'Fitness',
        imgUrl:'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cHVzaHVwc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
        title:'Pushups',
        content:"If done correctly, the push-up can strengthen the chest, shoulders, triceps, and even the core trunk muscles, all at one time.Push-ups can be done at any level of fitness, says Cotton: For someone who is at a more beginning level, start by pushing from the kitchen-counter height. Then work your way to a desk, a chair, the floor with bent knees, and, finally, the floor on your toes.",
        fullcontent:"If done correctly, the push-up can strengthen the chest, shoulders, triceps, and even the core trunk muscles, all at one time.Push-ups can be done at any level of fitness, says Cotton: For someone who is at a more beginning level, start by pushing from the kitchen-counter height. Then work your way to a desk, a chair, the floor with bent knees, and, finally, the floor on your toes.",
    },
    {
        id:50,
        category:'Fitness',
        imgUrl:'https://thumbs.dreamstime.com/b/running-athlete-man-29566643.jpg',
        title:'Running',
        content:"Running is a form of aerobic exercise, and it can help improve cardiovascular fitness and bone strength. Jogging is a less intense form of running and may be best for beginners.People can often improve their running endurance through interval running, which involves running for a certain distance or time and then switching to walking before running again. Alternatively, people can switch between running and sprinting.Sprint interval training may help decrease body fat, increase aerobic capacity, and increase peak running speed.",
        fullcontent:"Running is a form of aerobic exercise, and it can help improve cardiovascular fitness and bone strength. Jogging is a less intense form of running and may be best for beginners.People can often improve their running endurance through interval running, which involves running for a certain distance or time and then switching to walking before running again. Alternatively, people can switch between running and sprinting.Sprint interval training may help decrease body fat, increase aerobic capacity, and increase peak running speed.",
    },
    {
        id:51,
        category:'Technology',
        imgUrl:'https://cdn.pixabay.com/photo/2018/01/02/08/11/block-chain-3055701__340.jpg',
        title:'Technology-4',
        content:'artificial intelligence (AI) and blockchain concepts are spreading at a phenomenal rate. Both technologies have distinct degree of technological complexity and multi-dimensional business implications. However, a common misunderstanding about blockchain concept, in particular, is that blockchain is decentralized and is not controlled by anyone. But the underlying development of a blockchain system is still attributed to a cluster of core developers. ',
        fullcontent:'artificial intelligence (AI) and blockchain concepts are spreading at a phenomenal rate. Both technologies have distinct degree of technological complexity and multi-dimensional business implications. However, a common misunderstanding about blockchain concept, in particular, is that blockchain is decentralized and is not controlled by anyone. But the underlying development of a blockchain system is still attributed to a cluster of core developers. '
    },
    {
        id:52,
        category:'Technology',
        imgUrl:'https://images.unsplash.com/photo-1534723328310-e82dad3ee43f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80',
        title:'Technology-5',
        content:'Tesla Chief Elon Musk is all geared up to deploy several humanoid robots named Tesla Bots in the Tesla factory. Four years ago, this Billionaire had said that they over relied on the robots and that resulted in a “production hell”. He had said that at certain jobs, humans are better than these humanoids.',
        fullcontent:'Tesla Chief Elon Musk is all geared up to deploy several humanoid robots named Tesla Bots in the Tesla factory. Four years ago, this Billionaire had said that they over relied on the robots and that resulted in a “production hell”. He had said that at certain jobs, humans are better than these humanoids.',
    },
    {
        id:52,
        category:'Tollywood',
        imgUrl:'https://pbs.twimg.com/media/FOjhBkIVcAIkdd_?format=jpg&name=large',
        title:'Bheemla Nayak',
        content:"Bheemla Nayak is a 2022 Indian Telugu-language action drama film directed by Saagar K Chandra from a screenplay by Trivikram Srinivas. It is a remake of the 2020 Malayalam film Ayyappanum Koshiyum and stars Pawan Kalyan, Rana Daggubati, Nithya Menen and Samyuktha Menon.The film is primarily shot in Hyderabad between January 2021 and February 2022 while being halted by the COVID-19 pandemic. It has music composed by Thaman S with cinematography by Ravi K. Chandran and editing by Naveen Nooli. Bheemla Nayak was theatrically released on 25 February 2022 and opened to positive reviews. The film grossed between ₹161–192.37 crore,[b] against a budget of over ₹70 crore.",
        fullcontent:"Bheemla Nayak is a 2022 Indian Telugu-language action drama film directed by Saagar K Chandra from a screenplay by Trivikram Srinivas. It is a remake of the 2020 Malayalam film Ayyappanum Koshiyum and stars Pawan Kalyan, Rana Daggubati, Nithya Menen and Samyuktha Menon.The film is primarily shot in Hyderabad between January 2021 and February 2022 while being halted by the COVID-19 pandemic. It has music composed by Thaman S with cinematography by Ravi K. Chandran and editing by Naveen Nooli. Bheemla Nayak was theatrically released on 25 February 2022 and opened to positive reviews. The film grossed between ₹161–192.37 crore,[b] against a budget of over ₹70 crore.",
    },


    
    {
        id:52,
        category:'Tollywood',
        imgUrl:'https://assets.gadgets360cdn.com/pricee/assets/product/202206/Sita-Ramam-poster_1656325728.jpg',
        title:'Sita Ramam',
        content:"Sita Ramam is a 2022 Indian Telugu-language period romantic drama film co-written and directed by Hanu Raghavapudi and produced by Vyjayanthi Movies and Swapna Cinema. The film stars Dulquer Salmaan, Mrunal Thakur (in her Telugu debut), Rashmika Mandanna and Sumanth. Set in 1964, Lieutenant Ram, an orphan Indian army officer serving at the Kashmir border, gets anonymous love letters from Sita Mahalakshmi. Ram is on a mission to find Sita and propose his love.",
        fullcontent:"Sita Ramam is a 2022 Indian Telugu-language period romantic drama film co-written and directed by Hanu Raghavapudi and produced by Vyjayanthi Movies and Swapna Cinema. The film stars Dulquer Salmaan, Mrunal Thakur (in her Telugu debut), Rashmika Mandanna and Sumanth. Set in 1964, Lieutenant Ram, an orphan Indian army officer serving at the Kashmir border, gets anonymous love letters from Sita Mahalakshmi. Ram is on a mission to find Sita and propose his love.",
    },
    {
        id:53,
        category:'Tollywood',
        imgUrl:' https://www.onlykollywood.com/wp-content/uploads/2022/06/vikram_movie_review.jpg',
        title:'Vikram',
        content:"Vikram is a 2022 Indian Tamil-language action thriller film written and directed by Lokesh Kanagaraj and produced by Raaj Kamal Films International.[8] The film stars Kamal Haasan, Vijay Sethupathi and Fahadh Faasil.[9][10] Kalidas Jayaram,[11] Narain and Chemban Vinod Jose play supporting roles while Suriya makes a cameo appearance as Rolex. The film's soundtrack and score are composed by Anirudh Ravichander, with cinematography handled by Girish Gangadharan and editing done by Philomin Raj. The film serves as the second installment in the Lokesh Cinematic Universe (LCU).[12] The plot follows a black-ops squad led by Agent Vikram, in which he aims to bring down a drug syndicate group called Vetti Vagaiyara, led by Sandhanam, who wants the missing drugs to be delivered to his boss Rolex.",
        fullcontent:"Vikram is a 2022 Indian Tamil-language action thriller film written and directed by Lokesh Kanagaraj and produced by Raaj Kamal Films International.[8] The film stars Kamal Haasan, Vijay Sethupathi and Fahadh Faasil.[9][10] Kalidas Jayaram,[11] Narain and Chemban Vinod Jose play supporting roles while Suriya makes a cameo appearance as Rolex. The film's soundtrack and score are composed by Anirudh Ravichander, with cinematography handled by Girish Gangadharan and editing done by Philomin Raj. The film serves as the second installment in the Lokesh Cinematic Universe (LCU).[12] The plot follows a black-ops squad led by Agent Vikram, in which he aims to bring down a drug syndicate group called Vetti Vagaiyara, led by Sandhanam, who wants the missing drugs to be delivered to his boss Rolex.",
    },

]
export default Data;